In [1]:
import numpy as np

In [3]:
x = np.arange(1,11)

print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
y = np.arange(11,21)

print(y)

[11 12 13 14 15 16 17 18 19 20]


In [5]:
print(x+y)

[12 14 16 18 20 22 24 26 28 30]


In [6]:
print(3*x)

[ 3  6  9 12 15 18 21 24 27 30]


In [7]:
print(x+10)

[11 12 13 14 15 16 17 18 19 20]


In [9]:
print(x**2)

[  1   4   9  16  25  36  49  64  81 100]


In [13]:
import math as ma
# sin cos

print(round(ma.sin(ma.pi),2))

0.0


$$x = (1,2,3)$$

$$np.sin(x) = (sin(1), sin(2), sin(3))$$

$$np.exp(x) = (e^1, e^2, e^3)$$

In [14]:
x = np.arange(-2*np.pi, 2*np.pi + np.pi, np.pi)

print(x)

[-6.28318531 -3.14159265  0.          3.14159265  6.28318531]


In [17]:
print(np.sin(x))

[ 2.4492936e-16 -1.2246468e-16  0.0000000e+00  1.2246468e-16
 -2.4492936e-16]


In [18]:
print(np.cos(x))

[ 1. -1.  1. -1.  1.]


In [23]:
print(x.ndim) #Dimencion del arreglo
print(x.size) #Tamaño del arreglo
print(x.shape) #(M, N)

1
5
(5,)


# Algebra lineal

$$\vec{x} = (1,2)$$
$$\vec{y} = (3,4)$$

## Producto interno

$$\vec{x} \cdot \vec{y} = 1 \cdot 3 + 2 \cdot 4$$

In [27]:
x = np.array([1,2])
y = np.array([3,4])

print(x.dot(y)) #producto punto x y -> y x

11


In [30]:
w = np.array([1,2,3])
z = np.array([4,5,6])

print(np.cross(w,z)) #producto cruz
print(np.cross(z,w))

[-3  6 -3]
[ 3 -6  3]


$$x + 2y = 5$$
$$3x + 4y = 6$$

In [33]:
A = np.array([[1,2], [3,4]])
B = np.array([5,6])

print(np.linalg.solve(A,B)) #Solucion al sitema de ecuaciones

[-4.   4.5]


## Estadistica

In [35]:
x = np.array([1,2,3])

print(np.mean(x)) #Media de los datos del arreglo

2.0
