# Numpy

Numpy es una libreria cientifica de Python, que sirve para manipular vectores y matrices

In [1]:
import numpy as np

In [2]:
x = [1,2,3]
y = [4,5,6]

print(x+y)

[1, 2, 3, 4, 5, 6]


$$x = (1,2,3)$$

$$y = (4,5,6)$$

$$x + y =(1+4, 2+5, 3+6) = (5,7,9)$$

In [4]:
x = np.array(x)
y = np.array(y)

print(x+y)

print(type(x))

[5 7 9]
<class 'numpy.ndarray'>


$$A = \begin{pmatrix}
1 & 2 \\
3 & 4 
\end{pmatrix}$$

$$B = \begin{pmatrix}
5 & 6 \\
7 & 8 
\end{pmatrix}$$

In [1]:
A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]

print(A+B)

[[1, 2], [3, 4], [5, 6], [7, 8]]


In [6]:
A = np.array(A)
B = np.array(B)

print(A+B)

[[ 6  8]
 [10 12]]


In [14]:
%time

X = list(range(1,101))
         
print(X)

Wall time: 0 ns
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [17]:
%time

Y = np.arange(1,101,1)

print(Y)

Wall time: 0 ns
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [28]:
%time

dt = 0.2

ñ = np.arange(1,11+dt,dt)

print(ñ)

Wall time: 0 ns
[ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11. ]


In [27]:
x = np.array([])

print(x)

x = np.append(x,2)

print(x)

[]
[2.]


In [29]:
z = np.zeros(10)

print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


```python

np.zeros((M,N))

```
Genera una matriz de M filas y N columnas

In [32]:
Z = np.zeros((100,100))

print(Z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [34]:
a = np.ones(20)

print(a)

A = np.ones((2,2))

print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [36]:
import random as ra

for i in range(len(z)):
    z[i] = ra.random()
    
print(z)

[0.19759212 0.04214611 0.83292796 0.56517307 0.77166045 0.32663601
 0.11274168 0.34908286 0.78643828 0.22756482]


```python

np.linspace(i, f, N)

```

Esto nos cra un vector qu va d $i$ hasta $f$ tal que $N$ es la canrtidad de numeros en ese arreglo

In [38]:
w = np.linspace(1,10,101)

print(w)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.54  1.63  1.72  1.81  1.9   1.99
  2.08  2.17  2.26  2.35  2.44  2.53  2.62  2.71  2.8   2.89  2.98  3.07
  3.16  3.25  3.34  3.43  3.52  3.61  3.7   3.79  3.88  3.97  4.06  4.15
  4.24  4.33  4.42  4.51  4.6   4.69  4.78  4.87  4.96  5.05  5.14  5.23
  5.32  5.41  5.5   5.59  5.68  5.77  5.86  5.95  6.04  6.13  6.22  6.31
  6.4   6.49  6.58  6.67  6.76  6.85  6.94  7.03  7.12  7.21  7.3   7.39
  7.48  7.57  7.66  7.75  7.84  7.93  8.02  8.11  8.2   8.29  8.38  8.47
  8.56  8.65  8.74  8.83  8.92  9.01  9.1   9.19  9.28  9.37  9.46  9.55
  9.64  9.73  9.82  9.91 10.  ]


$$salto = \frac{n_f - n_i}{N}$$